# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'switch.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class GamepadWidget(QtWidgets.QWidget):
    def _as_init__(self, parent = None):

        QtWidgets.QWidget.__init__(self, parent)

        latitudeLabel = QtWidgets.QLabel(self.tr("Latitude:"))
        self.latitudeSpinBox = QtWidgets.QDoubleSpinBox()
        self.latitudeSpinBox.setRange(-90.0, 90.0)
        self.latitudeSpinBox.setDecimals(5)

        longitudeLabel = QtWidgets.QLabel(self.tr("Longitude:"))
        self.longitudeSpinBox = QtWidgets.QDoubleSpinBox()
        self.longitudeSpinBox.setRange(-180.0, 180.0)
        self.longitudeSpinBox.setDecimals(5)

        # # self.connect(self.latitudeSpinBox,
        # #     SIGNAL("valueChanged(double)"),
        # #     self, SIGNAL("latitudeChanged(double)"))
        # # self.connect(self.longitudeSpinBox,
        # #     SIGNAL("valueChanged(double)"),
        # #     self, SIGNAL("longitudeChanged(double)"))

        layout = QtWidgets.QGridLayout(self)
        layout.addWidget(latitudeLabel, 0, 0)
        layout.addWidget(self.latitudeSpinBox, 0, 1)
        layout.addWidget(longitudeLabel, 1, 0)
        layout.addWidget(self.longitudeSpinBox, 1, 1)
    
    def __init__(self, btns: dict = {}, *args, **kwargs):
        super(GamepadWidget, self).__init__(*args, **kwargs)

        layout = QtWidgets.QGridLayout(self)

        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(True)

        for i, n in enumerate(["A", "B"]):
            cl = QtWidgets.QLabel("") # 64, 64, "white")
            cl.setGeometry(QtCore.QRect(100 + i * 50, 140, 64, 64))
            cl.setVisible(True)
            cl.setSizePolicy(sizePolicy)
            cl.setText("asdf")
            cl.setMinimumSize(QtCore.QSize(64, 64))
            cl.setStyleSheet(f"image: url(:/img/Switch/Switch_{n}.png)")
            cl.setObjectName(f"cl_label_{n}")
            layout.addWidget(cl)

            print(i, n)

        self.setLayout(layout)

        self.setSizePolicy(QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding))

from ClickableLabel import ClickableLabel
import res_rc
